=== CAFAudit/audit-service/caf-audit-schema/src/main/resources/schema/AuditedApplication.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--

    Copyright 2015-2017 Hewlett Packard Enterprise Development LP.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:aa="https://cafaudit.github.io/audit-service/schema/AuditedApplication.xsd"
        targetNamespace="https://cafaudit.github.io/audit-service/schema/AuditedApplication.xsd"
        elementFormDefault="qualified">

  <element name="AuditedApplication">
    <complexType>
      <sequence>
        <element name="ApplicationId" type="string" />
        <element name="AuditEvents">
          <complexType>
            <sequence>
              <element name="AuditEvent" type="aa:AuditEvent" maxOccurs="unbounded" />
            </sequence>
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>

  <complexType name="AuditEvent">
    <sequence>
      <element name="TypeId" type="string" />
      <element name="CategoryId" type="string" />
      <element name="Params">
        <complexType>
          <sequence>
            <element name="Param" type="aa:AuditEventParam" maxOccurs="unbounded" />
          </sequence>
        </complexType>
      </element>
    </sequence>
  </complexType>

  <complexType name="AuditEventParam">
    <sequence>
      <element name="Name" type="string" />
      <element name="Type" type="aa:AuditEventParamType" />
      <element name="IndexingHint" type="aa:AuditEventParamIndexingHint" minOccurs="0"/>
      <element name="Constraints" type="aa:AuditEventParamConstraints" minOccurs="0"/>
      <element name="ColumnName" type="string" minOccurs="0" />
      <element name="Description" type="string" />
    </sequence>
  </complexType>

  <complexType name="AuditEventParamConstraints">
      <sequence>
          <element name="MinLength" type="integer" minOccurs="0" default="1" />
          <element name="MaxLength" type="integer" minOccurs="0" default="65000" />
      </sequence>
  </complexType>

  <simpleType name="AuditEventParamType">
    <restriction base="string">
      <enumeration value="string" />
      <enumeration value="short" />
      <enumeration value="int" />
      <enumeration value="long" />
      <enumeration value="float" />
      <enumeration value="double" />
      <enumeration value="boolean" />
      <enumeration value="date" />
    </restriction>
  </simpleType>

  <simpleType name="AuditEventParamIndexingHint">
    <restriction base="string">
      <enumeration value="fulltext" />
      <enumeration value="keyword" />
    </restriction>
  </simpleType>

</schema>

=== CAFAudit/audit-service/caf-audit-maven-plugin/src/test/resources/xml/InvalidAuditConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2015-2017 Hewlett Packard Enterprise Development LP.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<AuditedApplication			
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://cafaudit.github.io/audit-service/schema/AuditedApplication.xsd" 
    xsi:schemaLocation="https://cafaudit.github.io/audit-service/schema/AuditedApplication.xsd"			
>
	<ApplicationId>ProductX</ApplicationId>
	<AuditEvents>
	  <AuditEvent>
		<TypeId>viewDocument</TypeId>
		<UnexpectedElement>This is here for unit test purposes.</UnexpectedElement>
		<Params>
		  <Param>
			<Name>docId</Name>
			<Type>long</Type>
			<Description>Identifies the document that was viewed</Description>
		  </Param>
		</Params>
	  </AuditEvent>
	  <AuditEvent>
		<TypeId>policyApplied</TypeId>
		<UnexpectedElement>This is here for unit test purposes.</UnexpectedElement>
		<Params>
		  <Param>
			<Name>PolicyId</Name>
			<Type>long</Type>
			<Description>Identifies the policy being applied</Description>
		  </Param>
		  <Param>
			<Name>policyName</Name>
			<Type>string</Type>
			<Description>The name of the policy being applied</Description>
		  </Param>
		  <Param>
			<Name>policyDef</Name>
			<Type>string</Type>
			<Description>The definition of the policy being applied</Description>
		  </Param>
		</Params>
	  </AuditEvent>	  
	</AuditEvents>
</AuditedApplication>

=== CAFAudit/audit-service/caf-audit-qa/sample-test-scripts/xml/CAFStorageService.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2015-2017 Hewlett Packard Enterprise Development LP.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<AuditedApplication
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.hpe.com/CAF/Auditing/Schema/AuditedApplication.xsd"
        xsi:schemaLocation="http://www.hpe.com/CAF/Auditing/Schema/AuditedApplication.xsd"
>
<ApplicationId>CAFStorageService</ApplicationId>
    <AuditEvents>
        <AuditEvent>
            <TypeId>apiRequest</TypeId>
            <CategoryId>apiEvents</CategoryId>
            <Params>
                <Param>
                    <Name>realmId</Name>
                    <Type>string</Type>
                    <Constraints>
                        <MinLength>1</MinLength>
                        <MaxLength>32</MaxLength>
                    </Constraints>
                    <Description>Realm identifier</Description>
                </Param>
                <Param>
                    <Name>containerId</Name>
                    <Type>string</Type>
                    <Constraints>
                        <MaxLength>32</MaxLength>
                    </Constraints>
                    <Description>Asset Container identifier</Description>
                </Param>
                <Param>
                    <Name>assetId</Name>
                    <Type>string</Type>
                    <Constraints>
                        <MinLength></MinLength>
                        <MaxLength></MaxLength>
                    </Constraints>
                    <Description>Asset identifier</Description>
                </Param>
                <Param>
                    <Name>revId</Name>
                    <Type>string</Type>
                    <Description>Asset Revision identifier</Description>
                </Param>
                <Param>
                    <Name>requestId</Name>
                    <Type>string</Type>
                    <Description>Request identifier</Description>
                </Param>
                <Param>
                    <Name>requestType</Name>
                    <Type>int</Type>
                    <Description>Request type</Description>
                </Param>
                <Param>
                    <Name>requestUri</Name>
                    <Type>string</Type>
                    <Description>Request URI</Description>
                </Param>
            </Params>
        </AuditEvent>
        <AuditEvent>
            <TypeId>apiResponse</TypeId>
            <CategoryId>apiEvents</CategoryId>
            <Params>
                <Param>
                    <Name>realmId</Name>
                    <Type>string</Type>
                    <Constraints>
                        <MinLength>1</MinLength>
                    </Constraints>
                    <Description>Realm identifier</Description>
                </Param>
                <Param>
                    <Name>requestId</Name>
                    <Type>string</Type>
                    <Constraints>
                        <MaxLength>32</MaxLength>
                    </Constraints>
                    <Description>Request identifier</Description>
                </Param>
                <Param>
                    <Name>statusCode</Name>
                    <Type>int</Type>
                    <Description>Request status code</Description>
                </Param>
                <Param>
                    <Name>errorMessage</Name>
                    <Type>string</Type>
                    <Constraints>
                        <MaxLength>32000000</MaxLength>
                    </Constraints>
                    <Description>Error message, if applicable</Description>
                </Param>
            </Params>
        </AuditEvent>
        <AuditEvent>
            <TypeId>blockPurged</TypeId>
            <CategoryId>internalEvents</CategoryId>
            <Params>
                <Param>
                    <Name>realmId</Name>
                    <Type>string</Type>
                    <Constraints>
                        <MaxLength>32</MaxLength>
                    </Constraints>
                    <Description>Realm identifier</Description>
                </Param>
                <Param>
                    <Name>rawSignature</Name>
                    <Type>string</Type>
                    <Constraints>
                        <MinLength></MinLength>
                        <MaxLength></MaxLength>
                    </Constraints>
                    <Description>Raw block signature</Description >
                </Param>
                <Param>
                    <Name>referenceLocation</Name>
                    <Type>string</Type>
                    <Constraints>
                        <MinLength></MinLength>
                        <MaxLength></MaxLength>
                    </Constraints>
                    <Description>Reference location for stored block</Description >
                </Param>
                <Param>
                    <Name>storageDeviceId</Name>
                    <Type>long</Type>
                    <Description>Storage device identifier</Description >
                </Param>
            </Params>
        </AuditEvent>
    </AuditEvents>
</AuditedApplication>

=== CAFAudit/audit-service/caf-audit-management-service/src/test/resources/xml/AuditConfigValid.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2015-2017 Hewlett Packard Enterprise Development LP.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<AuditedApplication
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns="http://www.hpe.com/CAF/Auditing/Schema/AuditedApplication.xsd"
		xsi:schemaLocation="http://www.hpe.com/CAF/Auditing/Schema/AuditedApplication.xsd"
>
	<ApplicationId>ApplicationX</ApplicationId>
	<AuditEvents>
		<AuditEvent>
			<TypeId>viewDocument</TypeId>
			<CategoryId>documentEvents</CategoryId>
			<Params>
				<Param>
					<Name>String_Param</Name>
					<Type>string</Type>
					<ColumnName>String_Param</ColumnName>
					<Description>Description for String_Param</Description>
				</Param>
				<Param>
					<Name>Int16_Param</Name>
					<Type>short</Type>
					<ColumnName>Int16_Param</ColumnName>
					<Description>Description for Int16_Param</Description>
				</Param>
				<Param>
					<Name>Int32_Param</Name>
					<Type>int</Type>
					<ColumnName>Int32_Param</ColumnName>
					<Description>Description for Int32_Param</Description>
				</Param>
				<Param>
					<Name>Int64_Param</Name>
					<Type>long</Type>
					<ColumnName>Int64_Param</ColumnName>
					<Description>Description for Int64_Param</Description>
				</Param>
				<Param>
					<Name>Float_Param</Name>
					<Type>float</Type>
					<ColumnName>Float_Param</ColumnName>
					<Description>Description for Float_Param</Description>
				</Param>
				<Param>
					<Name>Double_Param</Name>
					<Type>double</Type>
					<ColumnName>Double_Param</ColumnName>
					<Description>Description for Double_Param</Description>
				</Param>
				<Param>
					<Name>Boolean_Param</Name>
					<Type>boolean</Type>
					<ColumnName>Boolean_Param</ColumnName>
					<Description>Description for Boolean_Param</Description>
				</Param>
				<Param>
					<Name>Date_Param</Name>
					<Type>date</Type>
					<ColumnName>Date_Param</ColumnName>
					<Description>Description for Date_Param</Description>
				</Param>
			</Params>
		</AuditEvent>
		<AuditEvent>
			<TypeId>viewDocument2</TypeId>
			<CategoryId>documentEvents2</CategoryId>
			<Params>
				<Param>
					<Name>String_Param2</Name>
					<Type>string</Type>
					<Constraints>
						<MaxLength>1000000</MaxLength>
					</Constraints>
					<ColumnName>String_Param2</ColumnName>
					<Description>Description for String_Param2</Description>
				</Param>
				<Param>
					<Name>Int16_Param2</Name>
					<Type>short</Type>
					<ColumnName>Int16_Param2</ColumnName>
					<Description>Description for Int16_Param2</Description>
				</Param>
			</Params>
		</AuditEvent>
		<AuditEvent>
			<TypeId>viewDocument3</TypeId>
			<CategoryId>documentEvents3</CategoryId>
			<Params>
				<Param>
					<Name>String_Param2</Name>
					<Type>string</Type>
					<Constraints>
						<MaxLength>32000000</MaxLength>
					</Constraints>
					<ColumnName>String_Param2</ColumnName>
					<Description>Description for String_Param2</Description>
				</Param>
			</Params>
		</AuditEvent>
	</AuditEvents>
</AuditedApplication>

=== CAFAudit/audit-service/caf-audit-maven-plugin/src/test/resources/xml/AuditConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2015-2017 Hewlett Packard Enterprise Development LP.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<AuditedApplication
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns="https://cafaudit.github.io/audit-service/schema/AuditedApplication.xsd"
		xsi:schemaLocation="https://cafaudit.github.io/audit-service/schema/AuditedApplication.xsd"
>
	<ApplicationId>ProductX</ApplicationId>
	<AuditEvents>
		<AuditEvent>
			<TypeId>viewDocument</TypeId>
			<CategoryId>documentEvents</CategoryId>
			<Params>
				<Param>
					<Name>String_Param</Name>
					<Type>string</Type>
					<Constraints>
						<MinLength>1</MinLength>
						<MaxLength>32</MaxLength>
					</Constraints>
					<Description>Description for String_Param</Description>
				</Param>
				<Param>
					<Name>Int16_Param</Name>
					<Type>short</Type>
					<Description>Description for Int16_Param</Description>
				</Param>
				<Param>
					<Name>Int32_Param</Name>
					<Type>int</Type>
					<Description>Description for Int32_Param</Description>
				</Param>
				<Param>
					<Name>Int64_Param</Name>
					<Type>long</Type>
					<Description>Description for Int64_Param</Description>
				</Param>
				<Param>
					<Name>Float_Param</Name>
					<Type>float</Type>
					<Description>Description for Float_Param</Description>
				</Param>
				<Param>
					<Name>Double_Param</Name>
					<Type>double</Type>
					<Description>Description for Double_Param</Description>
				</Param>
				<Param>
					<Name>Boolean_Param</Name>
					<Type>boolean</Type>
					<Description>Description for Boolean_Param</Description>
				</Param>
				<Param>
					<Name>Date_Param</Name>
					<Type>date</Type>
					<Description>Description for Date_Param</Description>
				</Param>
			</Params>
		</AuditEvent>
	</AuditEvents>
</AuditedApplication>

=== CAFAudit/audit-service/caf-audit-qa/sample-test-scripts/xml/AuditEventsConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<AuditedApplication
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns="http://www.hpe.com/CAF/Auditing/Schema/AuditedApplication.xsd"
		xsi:schemaLocation="http://www.hpe.com/CAF/Auditing/Schema/AuditedApplication.xsd"
>
	<ApplicationId>TestApplication</ApplicationId>
	<AuditEvents>
		<AuditEvent>
			<TypeId>TestEvent1</TypeId>
			<CategoryId>TestCategory1</CategoryId>
			<Params>
				<Param>
					<Name>StringType</Name>
					<Type>string</Type>
					<ColumnName>StringType</ColumnName>
					<Description>Description for StringType</Description>
				</Param>
				<Param>
					<Name>Int16Type</Name>
					<Type>short</Type>
					<ColumnName>Int16Type</ColumnName>
					<Description>Description for Int16Type</Description>
				</Param>
				<Param>
					<Name>Int32Type</Name>
					<Type>int</Type>
					<ColumnName>Int32Type</ColumnName>
					<Description>Description for Int32Type</Description>
				</Param>
				<Param>
					<Name>Int64Type</Name>
					<Type>long</Type>
					<ColumnName>Int64Type</ColumnName>
					<Description>Description for Int64Type</Description>
				</Param>
				<Param>
					<Name>FloatType</Name>
					<Type>float</Type>
					<ColumnName>FloatType</ColumnName>
					<Description>Description for FloatType</Description>
				</Param>
				<Param>
					<Name>DoubleType</Name>
					<Type>double</Type>
					<ColumnName>DoubleType</ColumnName>
					<Description>Description for DoubleType</Description>
				</Param>
				<Param>
					<Name>BooleanType</Name>
					<Type>boolean</Type>
					<ColumnName>BooleanType</ColumnName>
					<Description>Description for BooleanType</Description>
				</Param>
				<Param>
					<Name>DateType</Name>
					<Type>date</Type>
					<ColumnName>DateType</ColumnName>
					<Description>Description for DateType</Description>
				</Param>
			</Params>
		</AuditEvent>
		<AuditEvent>
			<TypeId>TestEvent2</TypeId>
			<CategoryId>TestCategory2</CategoryId>
			<Params>
				<Param>
					<Name>StringType2</Name>
					<Type>string</Type>
					<ColumnName>StringType2</ColumnName>
					<Description>Description for StringType2</Description>
				</Param>
				<Param>
					<Name>Int16Type2</Name>
					<Type>short</Type>
					<ColumnName>Int16Type2</ColumnName>
					<Description>Description for Int16Type2</Description>
				</Param>
			</Params>
		</AuditEvent>
		<AuditEvent>
			<TypeId>TestEvent3</TypeId>
			<CategoryId>TestCategory3</CategoryId>
			<Params>
				<Param>
					<Name>StringType3</Name>
					<Type>string</Type>
					<ColumnName>StringType3</ColumnName>
					<Description>Description for StringType3</Description>
				</Param>
				<Param>
					<Name>DateType2</Name>
					<Type>date</Type>
					<ColumnName>DateType2</ColumnName>
					<Description>Description for DateType2</Description>
				</Param>
			</Params>
		</AuditEvent>
	</AuditEvents>
</AuditedApplication>

=== CAFAudit/audit-service/caf-audit-binding-elasticsearch/test-case/events.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2015-2024 Open Text.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<AuditedApplication
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://cafaudit.github.io/audit-service/schema/AuditedApplication.xsd"
    xsi:schemaLocation="https://cafaudit.github.io/audit-service/schema/AuditedApplication.xsd"
>
    <ApplicationId>TestAuditEvents</ApplicationId>
    <AuditEvents>
        <AuditEvent>
            <TypeId>TestEvent1</TypeId>
            <CategoryId>TestCategory1</CategoryId>
            <Params>
                <Param>
                    <Name>StringType</Name>
                    <Type>string</Type>
                    <ColumnName>StringType</ColumnName>
                    <Description>Description for StringType</Description>
                </Param>
                <Param>
                    <Name>StringKeywordType</Name>
                    <Type>string</Type>
                    <IndexingHint>keyword</IndexingHint>
                    <Description>Description for StringKeywordType</Description>
                </Param>
                <Param>
                    <Name>StringTextType</Name>
                    <Type>string</Type>
                    <IndexingHint>fulltext</IndexingHint>
                    <Description>Description for StringTextType</Description>
                </Param>
                <Param>
                    <Name>StringWithConstraintsType</Name>
                    <Type>string</Type>
                    <Constraints>
                        <MinLength>1</MinLength>
                        <MaxLength>100</MaxLength>
                    </Constraints>
                    <Description>Description for StringType</Description>
                </Param>
                <Param>
                    <Name>ShortType</Name>
                    <Type>short</Type>
                    <ColumnName>ShortType</ColumnName>
                    <Description>Description for Int16Type</Description>
                </Param>
                <Param>
                    <Name>IntType</Name>
                    <Type>int</Type>
                    <ColumnName>IntType</ColumnName>
                    <Description>Description for Int32Type</Description>
                </Param>
                <Param>
                    <Name>LongType</Name>
                    <Type>long</Type>
                    <ColumnName>LongType</ColumnName>
                    <Description>Description for Int64Type</Description>
                </Param>
                <Param>
                    <Name>FloatType</Name>
                    <Type>float</Type>
                    <ColumnName>FloatType</ColumnName>
                    <Description>Description for FloatType</Description>
                </Param>
                <Param>
                    <Name>DoubleType</Name>
                    <Type>double</Type>
                    <ColumnName>DoubleType</ColumnName>
                    <Description>Description for DoubleType</Description>
                </Param>
                <Param>
                    <Name>BooleanType</Name>
                    <Type>boolean</Type>
                    <ColumnName>BooleanType</ColumnName>
                    <Description>Description for BooleanType</Description>
                </Param>
                <Param>
                    <Name>DateType</Name>
                    <Type>date</Type>
                    <ColumnName>DateType</ColumnName>
                    <Description>Description for DateType</Description>
                </Param>
            </Params>
        </AuditEvent>
        <AuditEvent>
            <TypeId>TestEvent2</TypeId>
            <CategoryId>TestCategory2</CategoryId>
            <Params>
                <Param>
                    <Name>StringType2</Name>
                    <Type>string</Type>
                    <ColumnName>StringType2</ColumnName>
                    <Description>Description for StringType2</Description>
                </Param>
                <Param>
                    <Name>ShortType2</Name>
                    <Type>short</Type>
                    <ColumnName>ShortType2</ColumnName>
                    <Description>Description for Int16Type2</Description>
                </Param>
            </Params>
        </AuditEvent>
        <AuditEvent>
            <TypeId>TestEvent3</TypeId>
            <CategoryId>TestCategory3</CategoryId>
            <Params>
                <Param>
                    <Name>StringType3</Name>
                    <Type>string</Type>
                    <ColumnName>StringType3</ColumnName>
                    <Description>Description for StringType3</Description>
                </Param>
                <Param>
                    <Name>DateType2</Name>
                    <Type>date</Type>
                    <ColumnName>DateType2</ColumnName>
                    <Description>Description for DateType2</Description>
                </Param>
            </Params>
        </AuditEvent>
    </AuditEvents>
</AuditedApplication>
