=== CAFAudit/audit-service/src/main/resources/schema/AuditedApplication.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:aa="http://www.hpe.com/CAF/Auditing/Schema/AuditedApplication.xsd"
        targetNamespace="http://www.hpe.com/CAF/Auditing/Schema/AuditedApplication.xsd"
        elementFormDefault="qualified">

  <element name="AuditedApplication">
    <complexType>
      <sequence>
        <element name="ApplicationId" type="string" />
        <element name="AuditEvents">
          <complexType>
            <sequence>
              <element name="AuditEvent" type="aa:AuditEvent" maxOccurs="unbounded" />
            </sequence>
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>

  <complexType name="AuditEvent">
    <sequence>
      <element name="TypeId" type="string" />
      <element name="CategoryId" type="string" />
      <element name="Params">
        <complexType>
          <sequence>
            <element name="Param" type="aa:AuditEventParam" maxOccurs="unbounded" />
          </sequence>
        </complexType>
      </element>
    </sequence>
  </complexType>

  <complexType name="AuditEventParam">
    <sequence>
      <element name="Name" type="string" />
      <element name="Type" type="aa:AuditEventParamType" />
      <element name="ColumnName" type="string" minOccurs="0" />
    </sequence>
  </complexType>

  <simpleType name="AuditEventParamType">
    <restriction base="string">
      <enumeration value="string" />
      <enumeration value="long" />
    </restriction>
  </simpleType>

</schema>

=== CAFAudit/audit-service/src/test/resources/xml/AuditConfigInvalid.xml
<?xml version="1.0" encoding="UTF-8"?>
<AuditedApplication
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns="http://www.hpe.com/CAF/Auditing/Schema/AuditedApplication.xsd"
		xsi:schemaLocation="http://www.hpe.com/CAF/Auditing/Schema/AuditedApplication.xsd"
>
	<InvalidElement>ApplicationX</InvalidElement>
	<AuditEvents>
		<AuditEvent>
			<TypeId>viewDocument</TypeId>
			<CategoryId>documentEvents</CategoryId>
			<Params>
				<Param>
					<Name>String_Param</Name>
					<Type>string</Type>
					<ColumnName>String_Param</ColumnName>
					<Description>Description for String_Param</Description>
				</Param>
			</Params>
		</AuditEvent>
	</AuditEvents>
</AuditedApplication>

=== CAFAudit/audit-service/src/test/resources/xml/AuditConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<AuditedApplication			
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.hpe.com/CAF/Auditing/Schema/AuditedApplication.xsd" 
    xsi:schemaLocation="http://www.hpe.com/CAF/Auditing/Schema/AuditedApplication.xsd"			
>
	<ApplicationId>ProductX</ApplicationId>
	<AuditEvents>
	  <AuditEvent>
		<TypeId>viewDocument</TypeId>
		<CategoryId>documentEvents</CategoryId>
		  <Params>
			  <Param>
				  <Name>param1</Name>
				  <Type>string</Type>
				  <Description>Description for param1</Description>
			  </Param>
			  <Param>
				  <Name>param2</Name>
				  <Type>short</Type>
				  <Description>Description for param2</Description>
			  </Param>
			  <Param>
				  <Name>param3</Name>
				  <Type>int</Type>
				  <Description>Description for param3</Description>
			  </Param>
			  <Param>
				  <Name>param4</Name>
				  <Type>long</Type>
				  <Description>Description for param4</Description>
			  </Param>
			  <Param>
				  <Name>param5</Name>
				  <Type>float</Type>
				  <Description>Description for param5</Description>
			  </Param>
			  <Param>
				  <Name>param6</Name>
				  <Type>date</Type>
				  <Description>Description for param6</Description>
			  </Param>
		  </Params>
	  </AuditEvent>
	</AuditEvents>
</AuditedApplication>
